## Part 1: Array Creation & Attributes (The Fundamentals) 

#### 1. Import the NumPy library with the alias np. 

In [1]:
import numpy as np

#### 2. Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5].

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

#### 3. Create a 1D array of 10 zeros.

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Create a 3x3 array filled with ones.

In [4]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 5. Create an array of all even integers from 10 to 50.

In [5]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 6. Create a 3x3 matrix with values ranging from 0 to 8. 

In [6]:
arr = np.arange(9).reshape([3,3])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Create a 4x4 identity matrix.

In [7]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 9. Create a 3x4 array filled with random numbers between 0 and 1. 

In [9]:
arr = np.random.rand(3,4)
arr

array([[0.89788795, 0.0418986 , 0.80317789, 0.7072799 ],
       [0.60141728, 0.24157994, 0.49711996, 0.6273043 ],
       [0.8076031 , 0.6665446 , 0.61456703, 0.19419645]])

#### 10. Create a 5x5 array with random integers from 1 to 100. 

In [10]:
arr = np.random.randint(1,101, size=(5,5))
arr

array([[56,  7, 24, 54, 42],
       [50, 30, 61, 22, 20],
       [15, 45, 82, 95, 70],
       [69, 69, 66, 33, 53],
       [76, 53, 94, 81, 59]])

#### 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape. 

In [11]:
arr = np.arange(25).reshape(5, 5)
arr.shape

(5, 5)

#### 12. For the same array arr, find its data type.

In [12]:
arr.dtype

dtype('int32')

#### 13. For the same array arr, find the total number of elements. 

In [13]:
arr.size

25

#### 14. Create the array [1, 2, 3] but make sure its data type is float. 

In [14]:
arr = np.array([1,2,3], dtype = float)
arr.dtype

dtype('float64')

#### 15. Convert the data type of an existing integer array to float.

In [15]:
arr = np.array([1,2,3,4])
arr.astype(float)

array([1., 2., 3., 4.])

## Part 2: Indexing & Slicing (Accessing Your Data) 

(For questions 16-35, use the following arrays):

arr_1d = np.arange(10)  
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  

#### 16. From arr_1d, get the first element.

In [16]:
arr_1d = np.arange(10)  
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

In [23]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr_1d[0]

0

#### 17. From arr_1d, get the last element. 

In [26]:
arr_1d[-1]

9

#### 18. From arr_1d, get the elements from index 2 up to index 5.

In [27]:
arr_1d[2:6]

array([2, 3, 4, 5])

#### 19. From arr_1d, get all elements in reverse order. 

In [31]:
arr_1d[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 20. From arr_2d, get the element at row 1, column 2 (which is 6).