## Part 1: Array Creation & Attributes (The Fundamentals) 

#### 1. Import the NumPy library with the alias np. 

In [1]:
import numpy as np

#### 2. Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5].

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

#### 3. Create a 1D array of 10 zeros.

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Create a 3x3 array filled with ones.

In [4]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 5. Create an array of all even integers from 10 to 50.

In [5]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 6. Create a 3x3 matrix with values ranging from 0 to 8. 

In [6]:
arr = np.arange(9).reshape([3,3])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Create a 4x4 identity matrix.

In [7]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 9. Create a 3x4 array filled with random numbers between 0 and 1. 

In [9]:
arr = np.random.rand(3,4)
arr

array([[0.97130161, 0.93471665, 0.27325172, 0.14075995],
       [0.2448587 , 0.32664681, 0.40237927, 0.41783067],
       [0.79784591, 0.78304826, 0.33376514, 0.01653733]])

#### 10. Create a 5x5 array with random integers from 1 to 100. 

In [10]:
arr = np.random.randint(1,101, size=(5,5))
arr

array([[ 2, 87, 83, 11, 99],
       [97,  5, 24, 28, 97],
       [85, 54, 43, 52,  4],
       [48, 86, 16, 75, 65],
       [91, 59, 87, 89, 68]])

#### 11. Given the array arr = np.arange(25).reshape(5, 5), find its shape. 

In [11]:
arr = np.arange(25).reshape(5, 5)
arr.shape

(5, 5)

#### 12. For the same array arr, find its data type.

In [12]:
arr.dtype

dtype('int32')

#### 13. For the same array arr, find the total number of elements. 

In [13]:
arr.size

25

#### 14. Create the array [1, 2, 3] but make sure its data type is float. 

In [14]:
arr = np.array([1,2,3], dtype = float)
arr.dtype

dtype('float64')

#### 15. Convert the data type of an existing integer array to float.

In [15]:
arr = np.array([1,2,3,4])
arr.astype(float)

array([1., 2., 3., 4.])

## Part 2: Indexing & Slicing (Accessing Your Data) 

(For questions 16-35, use the following arrays):

arr_1d = np.arange(10)  
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  

#### 16. From arr_1d, get the first element.

In [16]:
arr_1d = np.arange(10)  
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

In [17]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr_1d[0]

0

#### 17. From arr_1d, get the last element. 

In [19]:
arr_1d[-1]

9

#### 18. From arr_1d, get the elements from index 2 up to index 5.

In [20]:
arr_1d[2:6]

array([2, 3, 4, 5])

#### 19. From arr_1d, get all elements in reverse order. 

In [21]:
arr_1d[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 20. From arr_2d, get the element at row 1, column 2 (which is 6).

In [22]:
arr_2d[1,2]

6

#### 21. From arr_2d, get the entire first row [1, 2, 3].

In [23]:
arr_2d[0]

array([1, 2, 3])

#### 22. From arr_2d, get the entire second column [2, 5, 8].

In [24]:
arr_2d[:,1]

array([2, 5, 8])

#### 23. From arr_2d, extract the sub-array [[1, 2], [4, 5]]. 

In [25]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

#### 24. Create a boolean mask to find all numbers in arr_1d that are greater than 5. 

In [26]:
arr_1d > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

#### 25. Use the boolean mask from the previous question to select the actual numbers from arr_1d. 

In [27]:
arr_1d[arr_1d > 5]

array([6, 7, 8, 9])

#### 26. In one line, select all numbers from arr_2d that are odd. 

arr_2d[arr_2d % 2 == 1]

#### 27. In arr_1d, replace all values greater than 5 with the value 0. 

In [28]:
arr_2d[arr_2d > 5] = 0
arr_2d

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

#### 28. From arr_1d, select the elements at indices 1, 3, and 7. 

In [29]:
arr_1d[[1,3,7]]

array([1, 3, 7])

#### 29. From arr_2d, select the first and third rows.

In [30]:
arr_2d[[0,2]]

array([[1, 2, 3],
       [0, 0, 0]])

#### 30. What is the difference between a slice (view) and a fancy index (copy)? Modify a slice of arr_1d and see if the original changes.

In [46]:
# slice view
slice_view = arr_1d[1:5]
slice_view[1] = 200
print("After modifiying slice_view: ", arr_1d)

# Fancy indexing
fancy_copy = arr_1d[[1,2,3,]]
fancy_copy[0] = 999
print("After modifying fancy_copy: ", arr_1d)

After modifiying slice_view:  [  0   1 200   3   4   5   6   7   8   9]
After modifying fancy_copy:  [  0   1 200   3   4   5   6   7   8   9]


#### 31. Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected.

In [50]:
arr_2d.copy()
arr_2d[:2] = 0
arr_2d # Yes the orginal array are affected

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 32. From arr_2d, get the diagonal elements [1, 5, 9]. 

In [54]:
change_element = arr_2d[:]
change_element[:] = [[1,2,3],
                     [4,5,6],
                     [7,8,9]]
change_element

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
diag = np.diag(arr_2d)
diag

array([1, 5, 9])